### ISSUE TITLE
Modifications for faster replay

### ISSUE THREAD

**Issue by PrateekChauhan0194** [Sam152/cypress-replay#5]
Hi Sam,

As the users don't have an access to create pull requests, may I please suggest you remove `delay: Date.now() - startTime,` from `recordRequests.ts` to enable faster replay?
If you don't want to remove it altogether, can we have a flag in place to opt-out of having the `delay` from the recorded stubs?

Cheers!

Prateek

**Comment by Sam152** [comment]
Hi Prateek,

It wasn't intentional to restrict access to create PRs, I'll try enable that.

I think a configuration option for removing the delay would be great, I found without it in some test cases it made tests replay differently and cause them to fail, so it would be handy to be able to switch on or off.

**Comment by Sam152** [comment]
Hi @PrateekChauhan0194, I've pushed a PR which addresses this issue.

**Comment by PrateekChauhan0194** [comment]
That's great. I just had a look at the PR. Thanks for the quick fix Sam.
